#!/bin/bash

sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:docker-maint/testing
sudo apt-get -y update
sudo apt-get -y upgrade

echo 'DOCKER_OPTS="-H tcp://0.0.0.0:2376 -D -g /var/lib/docker -H unix://"' | sudo tee /etc/default/docker
sudo ln -s /usr/bin/docker /usr/bin/docker.io
sudo service docker restart

